- id: '1546505457362'
  alias: Autotallissa liiketta
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.notifier_name
    data:
      data: {}
      message: Liiketta autotallissa
- id: '1546505574625'
  alias: Alaovella liikettä
  trigger:
  - entity_id: binary_sensor.ip_camera_alaovi_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data: {}
      message: Alaovella liiketta
    service: notify.notifier_name
- id: '1548368982585'
  alias: Tehostettu IV
  trigger:
  - entity_id: binary_sensor.korkea_kosteus
    platform: state
    to: 'on'
  - above: '950'
    entity_id: sensor.netatmo_netatmo_co2
    platform: numeric_state
  - above: '950'
    entity_id: sensor.netatmo_sisalisa_co2
    platform: numeric_state
  condition: []
  action:
  - data:
      address: 53
      hub: hub1
      unit: 1
      value: [55,0]
    service: modbus.write_register
  - data:
      message: IV Tehostettu
    service: notify.notifier_name
- id: '1548369086316'
  alias: Normaali IV
  trigger:
  - entity_id: binary_sensor.korkea_kosteus
    for: 0:15:0
    platform: state
    to: 'off'
  - entity_id: binary_sensor.korkea_co2
    for: 0:15:0
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.korkea_co2
    state: 'off'
  - condition: state
    entity_id: binary_sensor.korkea_kosteus
    state: 'off'
  action:
  - data:
      address: 53
      unit: 1
      hub: hub1
      value: [40,0]
    service: modbus.write_register
  - data:
      message: IV normaali
    service: notify.notifier_name
- id: '1548369262074'
  alias: Autotallin ovi auki
  trigger:
  - entity_id: cover.garage
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: Autotallin ovi auki
    service: notify.notifier_name
- id: '1548369345665'
  alias: Pyykinpesukone on valmis
  trigger:
  - entity_id: sensor.washing_machine
    for: '120'
    platform: state
    to: Ready
  condition: []
  action:
  - data:
      message: Pyykinpesukone on valmis
    service: notify.notifier_name
- id: '1548876201080'
  alias: Alakerran valot päälle
  trigger:
  - above: '0'
    entity_id: sensor.fibaro_system_unknown_type_0801_id_1002_burglar
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: light.alakerran_olohuone
    service: light.turn_on
- id: '1548876449017'
  alias: Alakerran valot pois päältä
  trigger:
  - below: '1'
    entity_id: sensor.fibaro_system_unknown_type_0801_id_1002_burglar
    for: 0:30:00
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: light.alakerran_olohuone
    service: light.turn_off
- alias: Set fan speed
  trigger:
    platform: state
    entity_id: input_number.fan_speed
  action:
    service: modbus.write_register
    data_template:
      value: [ "{{ states.input_number.fan_speed.state|int }}", 0]
      unit: 1
      address: 53
      hub: hub1
- alias: Set fan speed number value
  trigger:
    platform: state
    entity_id: sensor.fan_speed
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.fan_speed
      value: "{{ states.sensor.fan_speed.state }}"
