- alias: Notify on Garage Open
  trigger:
    entity_id: cover.garage
    from: closed
    platform: state
    to: open
  action:
    service: notify.NOTIFIER_NAME
    data:
      message: Garage door open
      data:
        push:
          badge: 1
  id: 09bd600b31214b67883adf48edae1805
- id: 9540cae190bd4e07a1f04b7e307dfc16
  alias: Notify on Washing Machine Ready
  trigger:
  - entity_id: sensor.washing_machine
    for:
      minutes: 2
    from: Washing
    platform: state
    to: Ready
  action:
  - data:
      data:
        push:
          badge: 1
      message: Washing machine ready
    service: notify.NOTIFIER_NAME
- id: '1544900779997'
  alias: Kosteus tehostus
  trigger:
  - entity_id: binary_sensor.korkea_kosteus
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      address: 53
      unit: 1
      value: 55
    service: modbus.write_register
  - data:
      data:
        push:
          badge: 1
      message: IV Tehostettu
    service: notify.NOTIFIER_NAME
- id: '1545295385092'
  alias: Normaali Kosteus
  trigger:
  - entity_id: binary_sensor.korkea_kosteus
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      address: 53
      unit: 1
      value: 39
    service: modbus.write_register
  - data:
      data:
        push:
          badge: 1
      message: IV Normaali
    service: notify.NOTIFIER_NAME
- id: '1546505457362'
  alias: Autotallissa liiketta
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data: {}
      message: Liiketta autotallissa
    service: notify.notifier_name
- id: '1546505574625'
  alias: Alaovella liikettä
  trigger:
  - entity_id: binary_sensor.ip_camera_alaovi_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data: {}
      message: Alaovella liiketta
    service: notify.notifier_name
