homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 12
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  # Customization file
  customize: !include customize.yaml

  auth_providers:
   - type: legacy_api_password
     #- type: homeassistant

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_access_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: WeatherTomorrow
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds

  - platform: modbus
    registers:
    - name: IV Raitisilman lampotila
      unit_of_measurement: °C
      slave: 1
      register: 6
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Tuloilman lampotila LTOn jalkeen X2
      unit_of_measurement: °C
      slave: 1
      register: 7
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Tuloilman lampotila X3
      unit_of_measurement: °C
      slave: 1
      register: 8
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Jateilman lampotila X4
      unit_of_measurement: °C
      slave: 1
      register: 9
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Poistoilman lampotila X5
      unit_of_measurement: °C
      slave: 1
      register: 10
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Poistoilman lampotila ennen LTO X8
      unit_of_measurement: °C
      slave: 1
      register: 11
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Paluuveden lampotila X8
      unit_of_measurement: °C
      slave: 1
      register: 12
      scale: 0.1
      count: 1
      register_type: holding
    - name: IV Poistoilman kosteus X5
      unit_of_measurement: '%'
      slave: 1
      register: 13
      count: 1
      register_type: holding
    - name: IV LTO hyotysuhde tulopuolella
      unit_of_measurement: '%'
      slave: 1
      register: 29
      count: 1
      register_type: holding
    - name: IV LTO hyotysuhde poistopuolella
      unit_of_measurement: '%'
      slave: 1
      register: 30
      count: 1
      register_type: holding
    - name: IV 48h kosteustason keskiarvo
      unit_of_measurement: '%'
      slave: 1
      register: 35
      count: 1
      register_type: holding
    - name: IV Tilatieto
      slave: 1
      register: 44
      count: 1
      register_type: holding
    - name: IV Lampotilan saatoportaat
      slave: 1
      register: 45
      count: 1
      register_type: holding
    - name: IV Huone Lampotilan keskiarvo
      slave: 1
      register: 46
      count: 1
      register_type: holding
    - name: IV Todellinen teho
      unit_of_measurement: '%'
      slave: 1
      register: 50
      count: 1
      register_type: holding
    - name: IV-Teho valitaan kayttopaneelilta
      unit_of_measurement: '%'
      slave: 1
      register: 53
      count: 1
      register_type: holding

  - platform: rest
    name: Kodinhoito Temperature
    resource: http://127.0.0.1:8080/device?id=C4:20:6C:AF:66:F0
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Kodinhoito Humidity
    resource: http://127.0.0.1:8080/device?id=C4:20:6C:AF:66:F0
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Kodinhoito Sensor Battery
    resource: http://127.0.0.1:8080/device?id=C4:20:6C:AF:66:F0
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Lastenhuone Temperature
    resource: http://192.168.1.237:8080/device?id=CC:F2:5E:65:0B:B4
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Lastenhuone Humidity
    resource: http://192.168.1.237:8080/device?id=CC:F2:5E:65:0B:B4
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Lastenhuone Sensor Battery
    resource: http://192.168.1.237:8080/device?id=CC:F2:5E:65:0B:B4
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Autotalli Temperature
    resource: http://127.0.0.1:8080/device?id=CD:3C:72:70:82:38
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Autotalli Humidity
    resource: http://127.0.0.1:8080/device?id=CD:3C:72:70:82:38
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Autotalli Battery
    resource: http://127.0.0.1:8080/device?id=CD:3C:72:70:82:38
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Makuuhuone Temperature
    resource: http://192.168.1.237:8080/device?id=D5:20:68:95:DA:7A
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Makuuhuone Humidity
    resource: http://192.168.1.237:8080/device?id=D5:20:68:95:DA:7A
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Makuuhuone Sensor Battery
    resource: http://192.168.1.237:8080/device?id=D5:20:68:95:DA:7A
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Olohuone Temperature
    resource: http://192.168.1.237:8080/device?id=F1:02:7F:A4:78:87
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Olohuone Humidity
    resource: http://192.168.1.237:8080/device?id=F1:02:7F:A4:78:87
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Olohuone Sensor Battery
    resource: http://192.168.1.237:8080/device?id=F1:02:7F:A4:78:87
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Jakotukki Temperature
    resource: http://192.168.1.237:8080/device?id=F6:74:12:E2:94:96
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Jakotukki Humidity
    resource: http://192.168.1.237:8080/device?id=F6:74:12:E2:94:96
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Jakotukki Sensor Battery
    resource: http://192.168.1.237:8080/device?id=F6:74:12:E2:94:96
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Suihku Temperature
    resource: http://127.0.0.1:8080/device?id=F9:30:8E:AC:62:B2
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Suihku Humidity
    resource: http://127.0.0.1:8080/device?id=F9:30:8E:AC:62:B2
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Suihku Sensor Battery
    resource: http://127.0.0.1:8080/device?id=F9:30:8E:AC:62:B2
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Ulkolampo Temperature
    resource: http://192.168.1.237:8080/device?id=CE:E5:44:DF:72:7E
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Ulkolampo Humidity
    resource: http://192.168.1.237:8080/device?id=CE:E5:44:DF:72:7E
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Ulkolampo Sensor Battery
    resource: http://192.168.1.237:8080/device?id=CE:E5:44:DF:72:7E
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: rest
    name: Auto Temperature
    resource: http://192.168.1.237:8080/device?id=F8:05:B0:FA:97:BE
    value_template: '{{ value_json.Temp }}'
    unit_of_measurement: °C
  - platform: rest
    name: Auto Humidity
    resource: http://192.168.1.237:8080/device?id=F8:05:B0:FA:97:BE
    value_template: '{{ value_json.Humidity }}'
    unit_of_measurement: '%'
  - platform: rest
    name: Auto Sensor Battery
    resource: http://192.168.1.237:8080/device?id=F8:05:B0:FA:97:BE
    value_template: '{{ value_json.Battery }}'
    unit_of_measurement: 'mV'

  - platform: min_max
    name: ruuvi humidity mean
    type: mean
    entity_ids:
      - sensor.jakotukki_humidity
      - sensor.kodinhoito_humidity
      - sensor.lastenhuone_humidity
      - sensor.makuuhuone_humidity
      - sensor.olohuone_humidity
      - sensor.suihku_humidity
            # - sensor.autotalli_humidity

        #- platform: min_max
        #  name: ruuvi humidity max
        #  type: max
        #  entity_ids:
        #    - sensor.jakotukki_humidity
        #    - sensor.kodinhoito_humidity
        #    - sensor.lastenhuone_humidity
        #    - sensor.makuuhuone_humidity
        #    - sensor.olohuone_humidity
        #    - sensor.suihku_humidity
        #          #- sensor.autotalli_humidity
      
  - platform: min_max
    name: ruuvi temperature mean
    type: mean
    entity_ids:
      - sensor.autotalli_temperature
        #      - sensor.jakotukki_temperature
      - sensor.kodinhoito_temperature
      - sensor.lastenhuone_temperature
      - sensor.makuuhuone_temperature
      - sensor.olohuone_temperature
      - sensor.suihku_temperature
      
        #  - platform: min_max
        #    name: ruuvi temperature max
        #    type: max
        #    entity_ids:
        #      - sensor.autotalli_temperature
        #        #      - sensor.jakotukki_temperature
        #      - sensor.kodinhoito_temperature
        #      - sensor.lastenhuone_temperature
        #      - sensor.makuuhuone_temperature
        #      - sensor.olohuone_temperature
        #      - sensor.suihku_temperature

        #  - platform: min_max
        #    #name: ruuvi temperature mean
        #    name: Sisalampo
        #    type: mean
        #    entity_ids:
        #      - sensor.autotalli_temperature
        #      - sensor.jakotukki_temperature
        #      - sensor.kodinhoito_temperature
        #      - sensor.lastenhuone_temperature
        #      - sensor.makuuhuone_temperature
        #      - sensor.olohuone_temperature
        #      - sensor.suihku_temperature

  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
      - signal_strength

  - platform: template
    sensors:
      iv_tila:
        friendly_name: "IV Tila"
        value_template: >-
          {% if is_state('sensor.iv_tilatieto', '0') %}
            normaali
          {% elif is_state('sensor.iv_tilatieto', '1') %}
            MaxJaahdytys
          {% elif is_state('sensor.iv_tilatieto', '2') %}
            MaxLammitys
          {% elif is_state('sensor.iv_tilatieto', '4') %}
            HataSeis
          {% elif is_state('sensor.iv_tilatieto', '8') %}
            Seis
          {% elif is_state('sensor.iv_tilatieto', '16') %}
            Poissa
          {% elif is_state('sensor.iv_tilatieto', '32') %}
            PitkaanPoissa
          {% elif is_state('sensor.iv_tilatieto', '46') %}
            LampotilaTehostus
          {% elif is_state('sensor.iv_tilatieto', '128') %}
            CO2Tehostus
          {% elif is_state('sensor.iv_tilatieto', '256') %}
            RHTehostus
          {% elif is_state('sensor.iv_tilatieto', '512') %}
            Tehostus
          {% elif is_state('sensor.iv_tilatieto', '1024') %}
            Ylipaineistus
          {% elif is_state('sensor.iv_tilatieto', '2048') %}
            Liesituuletin
          {% elif is_state('sensor.iv_tilatieto', '4096') %}
            KeskusPolynimuri
          {% elif is_state('sensor.iv_tilatieto', '8192') %}
            SLPJaahdytys
          {% elif is_state('sensor.iv_tilatieto', '16384') %}
            KesaYoJaahdytys
          {% elif is_state('sensor.iv_tilatieto', '32768') %}
            EDXSulatus
          {% else %}
            JokuMuuMika
          {% endif %}
      iv_lamposaato:
        friendly_name: "Lampotilasaadin"
        value_template: >-
          {% if is_state('sensor.iv_lampotilan_saatoportaat', '0') %}
            EiMitaan
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '1') %}
            Jaahdytys
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '2') %}
            LTO
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '4') %}
            Lammitys
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '5') %}
            PorrasViive
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '6') %}
            KesaYoViilennys
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '7') %}
            Kaynnistys
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '8') %}
            Seis
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '9') %}
            LTOPuhdistus
          {% elif is_state('sensor.iv_lampotilan_saatoportaat', '10') %}
            EXTYksikonSulatus
          {% else %}
            MikaLie
          {% endif %}
      garage_status:
        friendly_name: 'Garage Status'
        value_template: >-
          {% if states.cover.garage %}
            {% if states.cover.garage.attributes["door_state"] == "open" %}
              Open
            {% elif states.cover.garage.attributes["door_state"] == "closed" %}
              Closed
            {% elif states.cover.garage.attributes["door_state"] == "opening" %}
              Opening
            {% elif states.cover.garage.attributes["door_state"] == "closing" %}
              Closing
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            n/a
          {% endif %}
      garage_car_present:
        friendly_name: 'Auto tallissa'
        value_template: >-
          {% if states.cover.garage %}
            {% if states.cover.garage.state == "open" %}
              n/a
            {% elif ((states.cover.garage.attributes["distance_sensor"] > 40) and (states.cover.garage.attributes["distance_sensor"] < 100)) %}
              Yes
            {% else %}
              No
            {% endif %}
          {% else %}
            n/a
          {% endif %}

      washing_machine:
        friendly_name: "Pesukone"
        value_template: >-
          {% if states('sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power')|float > 3 %}
             Washing
          {% elif states('sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power')|float > 1 %}
             Ready
          {% else %}
             Off
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      korkea_kosteus:
        friendly_name: "Korkea Kosteus"
        #delay_off:
        #  minutes: 1
        entity_id:
          - sensor.sisakosteus
        value_template: '{{ states.sensor.sisakosteus.attributes.max_value|float - 10 > states.sensor.sisakosteus.attributes.mean|float }}'
  - platform: template
    sensors:
      autotalli_kosteus:
        friendly_name: "Autotalli Kosteus"
        #delay_off:
        #  minutes: 1
        entity_id:
          - sensor.sisakosteus
          - sensor.autotalli_humidity
        value_template: '{{ states.sensor.autotalli_humidity|float - 10 > states.sensor.sisakosteus.attributes.mean|float }}'

switch:
  platform: modbus
  coils:
    - name: IV Poissa
      slave: 1
      coil: 1
    - name: IV Pitkaan Poissa
      slave: 1
      coil: 2
    - name: IV Liesituuletin
      slave: 1
      coil: 4
    - name: IV Kosteus Tehostus
      slave: 1
      coil: 9
    - name: IV Tehostus
      slave: 1
      coil: 10
    - name: IV Lampotila Tehostus
      slave: 1
      coil: 11
    - name: IV Jaahdytys sallittu
      slave: 1
      coil: 52
    - name: IV Lammitus sallittu
      slave: 1
      coil: 54
  #registers:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

bmw_connected_drive:
  bmw530e:
    username: !secret bmw_username
    password: !secret bmw_password
    region: rest_of_world

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 19200
  stopbits: 1
  bytesize: 8
  parity: N

ios:

device_tracker:
  - platform: unifi
    host: !secret unifi_address
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
    ssid_filter:
      - !secret unifi_ssid

weather:
  - platform: yweather
        #  - platform: darksky
        #api_key: !secret darksky_apikey
    language: fi
    name: Saa
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - icon
      - temperature
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low

plant:
  Sisalla:
    sensors:
      temperature: sensor.sisalampo
      moisture: sensor.sisakosteus

recorder:
  purge_keep_days: 10

zwave:
  usb_path: /dev/ttyACM0

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: arlo

#homekit:

cover:
  platform: opengarage
  covers:
      garage:
        host: 192.168.200.100
        device_key: !secret garage_key
        name: garage

notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

