name: Mollin Luola
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
#  - name: Example
  - tab_icon: mdi:home-assistant
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The entities card will take a list of entities and show their state.
#      - type: entities
#        # Title of the entities card
#        title: Example
#        # The entities here will be shown in the same order as specified.
#        entities:
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_livingroom
#          - input_boolean.switch_tv
#
#        # The filter card will filter available entities for certain criteria
#        # and render it as type 'entities'.
#      - type: entity-filter
#        # Filter criteria. They are all optional.
#        filter:
#          - domain: input_boolean
#            state: 'on'
#        # This config will be passed to the card rendering the filter results
#        card_config:
#          title: Input booleans that are on
#
      - type: plant-status
        entity: plant.sisalla

      - type: glance
        title: Ilmasto
        entities:
          - sensor.sisalampo
          - sensor.sisakosteus
          - sensor.ulkolampo_temperature

      - type: weather-forecast
        name: Saa
        #entity: weather.yweather
        entity: weather.dark_sky

      - type: glance
        title: Auto
        entities:
          - lock.530e_iperformance_lock
          - sensor.530e_iperformance_charging_level_hv
          - binary_sensor.530e_iperformance_connection_status
          - sensor.530e_iperformance_remaining_range_total
          - sensor.auto_temperature
          - sensor.auto_humidity

  - tab_icon: mdi:air-conditioner
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*iv*'
         card_config:
           title: Ilmanvaihto

  - tab_icon: mdi:car
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*530e*'
         card_config:
           title: Auto

  - tab_icon: mdi:washing-machine
    cards:
       - type: glance
         title: Pesukone Kaynnissa
         entities:
           - binary_sensor.washing_machine_running
       - type: entity-filter
         filter:
           - entity_id: '*philio*'
         card_config:
           title: Pyykinpesukone

  - tab_icon: mdi:garage
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*fibaro_system_fgms001zw5*'
         card_config:
           title: Liiketunnistin

  - tab_icon: mdi:chip
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*temperature*'
         card_config:
           title: Lampotilat
       - type: entity-filter
         filter:
           - entity_id: '*humidity*'
         card_config:
           title: Kosteus
       - type: entity-filter
         filter:
           - entity_id: '*battery*'
         card_config:
           title: Patterit

# sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power


    # Specify a tab_icon if you want the view tab to be an icon.
#  - tab_icon: mdi:home-assistant
#    # Name of the view. Will be used as the tooltip for tab icon
#    name: Second view
#    cards:
#      - type: entities
#        title: Lots of Kitchen AC
#        entities:
#            # It is totally possible to render duplicates.
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen

