name: Mollin Luola
views:
  - icon: mdi:home-assistant
    theme: dark-mode
    cards:

      - type: horizontal-stack
        cards:
           - type: entity-filter
             #title: Pesukone Kaynnissa
             entities:
               - entity: binary_sensor.washing_machine_running
                 icon: mdi:washing-machine
                 name: Pyykinpesu
                 style: "color: yellow"
             state_filter:
               - "on"
             show_empty: false
             card:
               type: glance
           - type: entity-filter
             #title: Pesukone Kaynnissa
             entities:
               - entity: binary_sensor.washing_machine_ready
                 icon: mdi:washing-machine
                 name: Pyykinpesu valmis
                 style: "color: green"
             state_filter:
               - "on"
             show_empty: false
             card:
               type: glance
           - type: entity-filter
             #title: Autotallin ovi
             entities:
               - entity: sensor.garage_status
                 icon: mdi:garage-open
                 name: Autotalli
             state_filter:
               - "Open"
             show_empty: false
             card:
               type: glance
           - type: conditional
             conditions:
               - entity: sensor.530e_iperformance_charging_status
                 state_not: "FINISHED_FULLY_CHARGED"
             card:
               type: glance
               entities:
                 - type: sensor
                   entity: sensor.530e_iperformance_charging_level_hv
                   icon: mdi:car-sports
                   hours_to_show: 24
                   accuracy: 96
                   name: Lataus %
           - type: conditional
             conditions:
               - entity: group.all_locks
                 state_not: "locked"
             card:
               type: glance
               entities:
                 - entity: group.all_locks
           - type: conditional
             conditions:
               - entity: group.all_lights
                 state_not: off
             card:
               type: glance
               entities:
                 - entity: group.all_lights
           - type: conditional
             conditions:
               - entity: sensor.iv_tila
                 state_not: "normaali"
             card:
               type: glance
               entities:
                 - entity: sensor.iv_tila

                   #icon: mdi:car-sports
                   #name: Lataus

             #      - type: horizontal-stack
             #        cards:
             #           - type: entity-filter
             #             title: Pesukone Kaynnissa
             #             entities:
             #               - entity: binary_sensor.washing_machine_running
             #                 icon: mdi:washing-machine
             #                 name: Pyykinpesu
             #             state_filter:
             #               - "on"
             #             show_empty: false
             #           - type: entity-filter
             #             title: Autotallin ovi
             #             entities:
             #               - entity: sensor.garage_status
             #                 icon: mdi:garage-open
             #                 name: Autotalli
             #             state_filter:
             #               - "Open"
             #             show_empty: false

             #      - type: glance
             #        entities:
             #          - entity: sensor.sisalampo
             #            icon: mdi:thermometer
             #          - entity: sensor.sisakosteus
             #            icon: mdi:water-percent
            #- entity: sensor.iv_raitisilman_lampotila
            #  icon: mdi:thermometer
            #  name: Ulkolampo
                 #      - type: entities
                 #        entities:
                 #          - entity: lock.polycontrol_danalock_v3_btze_locked
                 #            #icon: mdi:thermometer
                 #            name: Etuovi
                 
      - type: horizontal-stack
        cards:
           - type: sensor
             entity: sensor.sisalampo
             name: Sisalla
             icon: mdi:thermometer
             hours_to_show: 24
             accuracy: 96
           - type: sensor
             entity: sensor.sisakosteus
             name: Sisalla
             icon: mdi:water-percent
             hours_to_show: 24
             accuracy: 96
           - type: sensor
             entity: sensor.iv_raitisilman_lampotila
             name: Ulkona
             icon: mdi:thermometer
             hours_to_show: 24
             accuracy: 96

      - type: weather-forecast
        entity: weather.saa
        #entity: weather.dark_sky
        #      - type: iframe
        #        url: https://embed.windy.com/embed2.html
        #      - type: glance
        #        name: Valot
        #        entities:
        #          - entity: light.alakerran_olohuone
        #            name: AK Olohuone
        #            tap_action: toggle
        #          - entity: light.hue_white_lamp_1
        #            name: AK Olohuone lamppu1
        #            #- entity: light.hue_white_lamp_2
        #          - entity: light.hue_white_lamp_3
        #            name: AK Olohuone lamppu3

        #      - type: horizontal-stack
        #        cards:
        #           - type: gauge
        #             title: Auton Akku
        #             unit_of_measurement: '%'
        #             entity: sensor.530e_iperformance_charging_level_hv
        #             severity:
        #               green: 90
        #               yellow: 45
        #               red: 20
        #
        #           - type: entities
        #             entities:
        #               - entity: sensor.530e_iperformance_charging_status
        #                 name: Lataus
        #               - entity: sensor.530e_iperformance_mileage
        #                 name: Km
        #               - entity: sensor.530e_iperformance_remaining_range_total
        #                 name: Range
        #               - entity: sensor.auto_temperature
        #                 name: Sisalampo

      - type: horizontal-stack
        cards:
           - type: picture-glance
             title: Terassi
             entities:
               - camera.52m18372b655e_terassi
             camera_image: camera.52m18372b655e_terassi

           - type: picture-glance
             title: Etuovi
             entities:
               - camera.52m1837fb65db_ulkoovi
             camera_image: camera.52m1837fb65db_ulkoovi

             #           - type: entities
             #             entities:
             #               - entity: sensor.530e_iperformance_mileage
             #                 icon: mdi:car-sports
             #           - type: glance
             #             entities:
             #               - entity: sensor.530e_iperformance_charging_level_hv
             #                 name: Varaus
             #               - entity: sensor.530e_iperformance_remaining_range_total
             #                 name: Range
             #               - sensor.530e_iperformance_charging_status
             #               - entity: sensor.auto_temperature
             #                 name: SisaLampotila
             #               - entity: binary_sensor.530e_iperformance_door_lock_state
             #                 name: Lukot


             #      - type: vertical-stack
             #        cards:
             #           - type: entities
             #             entities:
             #               - entity: sensor.530e_iperformance_mileage
             #                 icon: mdi:car-sports
             #           - type: glance
             #             entities:
             #               - entity: sensor.530e_iperformance_charging_level_hv
             #                 name: Varaus
             #               - entity: sensor.530e_iperformance_remaining_range_total
             #                 name: Range
             #               - sensor.530e_iperformance_charging_status
             #               - entity: sensor.auto_temperature
             #                 name: SisaLampotila
             #               - entity: binary_sensor.530e_iperformance_door_lock_state
             #                 name: Lukot
                #- type: history-graph
                #  title: Battery Status
                #  entities:
                #   - sensor.530e_iperformance_charging_level_hv
                #      - type: glance
                #        title: Auto
                #        entities:
                #          - lock.530e_iperformance_lock
                #          - sensor.530e_iperformance_charging_level_hv
                #          - binary_sensor.530e_iperformance_connection_status
                #          - sensor.530e_iperformance_remaining_range_total
                #          - sensor.auto_temperature
                #          - sensor.auto_humidity

  - icon: mdi:air-conditioner
    title: ilmanvaihto
    type: vertical-stack
    cards:
       - type: glance
         entities:
           - entity: sensor.iv_raitisilman_lampotila
             name: Ulkolampotila
           - entity: sensor.iv_poistoilman_kosteus_x5
             name: Kosteus, Poisto
           - entity: switch.iv_tehostus
             name: Tehostus
           - entity: sensor.iv_todellinen_teho
             name: Teho
           - entity: switch.iv_poissa
             name: Poissa
             tap_action: toggle

       - type: glance
         entities:
           - entity: switch.iv_jaahdytys_sallittu
             name: Jaahdytys Sallittu
             tap_action: toggle
           - entity: switch.iv_lammitus_sallittu
             name: Lammitys Sallittu
             tap_action: toggle
           - entity: switch.iv_pitkaan_poissa
             name: Pitkaan Poissa
             tap_action: toggle
           - entity: switch.iv_kosteus_tehostus
             name: Kosteus Tehostus
             tap_action: toggle
           - entity: sensor.iv_tilatieto
             name: Tila

       - type: entities
         entities:
           - entity: sensor.iv_48h_kosteustason_keskiarvo
           - entity: sensor.iv_jateilman_lampotila_x4
           - entity: sensor.iv_lampotilan_saatoportaat
           - entity: sensor.iv_lto_hyotysuhde_poistopuolella
           - entity: sensor.iv_lto_hyotysuhde_tulopuolella
           - entity: sensor.iv_lamposaato
           - entity: sensor.iv_tila
           - entity: sensor.iv_paluuveden_lampotila_x8
           - entity: sensor.iv_poistoilman_lampotila_ennen_lto_x8
           - entity: sensor.iv_poistoilman_lampotila_x5
           - entity: sensor.iv_tuloilman_lampotila_lton_jalkeen_x2
           - entity: sensor.iv_tuloilman_lampotila_x3
           - entity: switch.iv_lampotila_tehostus
             #- entity: switch.iv_liesituuletin
             #card:
             #  title: Ilmanvaihto

  - icon: mdi:car
    type: vertical-stack
    cards:
       - type: picture-entity
         title: BMW 530e
         image: https://cdn.drivemag.net/media/default/0001/42/bmw-5-series-530e-iperformance-06-9939-default-large.jpeg
         entity: sensor.530e_iperformance_mileage
         name: Mileage
       - type: glance
         entities: 
          - entity: sensor.530e_iperformance_charging_level_hv
            name: Varaus
          - entity: sensor.530e_iperformance_remaining_range_total
            name: Range
          - sensor.530e_iperformance_charging_status
            #- binary_sensor.530e_iperformance_charging_status
          - entity: sensor.auto_temperature
            name: SisaLampotila
          - entity: binary_sensor.530e_iperformance_door_lock_state
            name: Lukot
            #- type: history-graph
            #  title: Battery Status
            #  entities:
            #   - sensor.530e_iperformance_charging_level_hv 
       - type: entities
         title: Ovi
         entities:
           - entity: cover.garage
             name: Autotallin Ovi
       - type: entities
         title: Liiketunnistin
         entities:
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
             name: Temperature
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
             name: Luminance
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_level
             name: Alarm Level
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_type
             name: Alarm Type
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
             name: Burglar
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_general
             name: General
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity
             name: Seismic Intensity
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_sourcenodeid
             name: Source Node ID


#  - icon: mdi:car
#    cards:
#       - type: entities
#         entities:
#           - group.bmw530e


  - icon: mdi:lightbulb
    cards:
      - type: glance
        name: Valot
        entities:
          - entity: light.alakerran_olohuone
            name: AK Olohuone
            tap_action: toggle
          - entity: light.hue_white_lamp_1
            name: AK Olohuone lamppu1
            #- entity: light.hue_white_lamp_2
          - entity: light.hue_white_lamp_3
            name: AK Olohuone lamppu3


  - icon: mdi:washing-machine
    cards:
       - type: glance
         title: Pesukone Kaynnissa
         entities:
           - binary_sensor.washing_machine_running
       - type: entities
         entities:
           - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_alarm_level
             name: Alarm Level
           - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_alarm_type
             name: Alarm Type
           - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_energy
             name: Energy
           - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
             name: Power
           - entity: switch.philio_technology_corporation_pan11_smart_energy_plug_in_switch_switch
             name: Switch


  - icon: mdi:chip
    cards:
       - type: entities
         title: Lampotilat
         entities:
           - entity: sensor.auto_temperature
           - entity: sensor.autotalli_temperature
           - entity: sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
           - entity: sensor.jakotukki_temperature
           - entity: sensor.kodinhoito_temperature
           - entity: sensor.lastenhuone_temperature
           - entity: sensor.makuuhuone_temperature
           - entity: sensor.olohuone_temperature
           - entity: sensor.ruuvi_temperature_max
           - entity: sensor.ruuvi_temperature_min
           - entity: sensor.suihku_temperature
           - entity: sensor.ulkolampo_temperature
           - entity: sensor.weathertomorrow_temperature
       - type: entities
         title: Kosteus
         entities:
           - entity: sensor.auto_humidity
           - entity: sensor.autotalli_humidity
           - entity: sensor.jakotukki_humidity
           - entity: sensor.kodinhoito_humidity
           - entity: sensor.lastenhuone_humidity
           - entity: sensor.makuuhuone_humidity
           - entity: sensor.olohuone_humidity
           - entity: sensor.ruuvi_humidity_max
           - entity: sensor.suihku_humidity
           - entity: sensor.ulkolampo_humidity
           - entity: sensor.weathertomorrow_humidity
       - type: entities
         title: Patterit
         entities:
           - entity: sensor.auto_sensor_battery
           - entity: sensor.autotalli_battery
           - entity: sensor.jakotukki_sensor_battery
           - entity: sensor.juhanis_iphone_battery_level
           - entity: sensor.juhanis_iphone_battery_state
           - entity: sensor.kodinhoito_sensor_battery
           - entity: sensor.lastenhuone_sensor_battery
           - entity: sensor.makuuhuone_sensor_battery
           - entity: sensor.olohuone_sensor_battery
           - entity: sensor.suihku_sensor_battery
           - entity: sensor.ulkolampo_sensor_battery

  - icon: mdi:play-network
    cards:
    - type: entities
      entities:
        - entity: media_player.alakerta
          name: Sonos Alakerta
        - entity: media_player.alakerta_2
          name: Chromecast Alakerta
        - entity: media_player.chromecastultra2983
          name: Chromecast Vierashuone
        - entity: media_player.chylakerta
          name: Chromecast Ylakerta
        - entity: media_player.olohuone
          name: Sonos Olohuone



# sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power


    # Specify a tab_icon if you want the view tab to be an icon.
#  - icon: mdi:home-assistant
#    # Name of the view. Will be used as the tooltip for tab icon
#    name: Second view
#    cards:
#      - type: entities
#        title: Lots of Kitchen AC
#        entities:
#            # It is totally possible to render duplicates.
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen

