name: Mollin Luola
views:
  - icon: mdi:home-assistant
    theme: dark-mode
    cards:
            #      - type: plant-status
            #        entity: plant.sisalla
            #      - type: glance
            #        title: Ilmasto
            #        entities:
            #          - sensor.sisalampo
            #          - sensor.sisakosteus
            #          - sensor.ulkolampo_temperature
      - type: vertical-stack
        cards:
           - type: picture
             image: https://platinumrealestate.vegas/wp-content/uploads/2017/02/buying-a-home.jpg
           - type: glance
             entities:
               - entity: sensor.sisalampo
                 icon: mdi:thermometer
               - entity: sensor.sisakosteus
                 icon: mdi:water-percent
               - entity: sensor.iv_raitisilman_lampotila
                 icon: mdi:thermometer
      - type: weather-forecast
        name: Saa
        entity: weather.yweather
        #entity: weather.dark_sky
      - type: vertical-stack
        cards:
           - type: picture-entity
             title: BMW 530e
             image: https://cdn.drivemag.net/media/default/0001/42/bmw-5-series-530e-iperformance-06-9939-default-large.jpeg
             entity: sensor.530e_iperformance_mileage
             name: Mileage
           - type: glance
             entities: 
              - entity: sensor.530e_iperformance_charging_level_hv
                name: Varaus
              - entity: sensor.530e_iperformance_remaining_range_total
                name: Range
              - sensor.530e_iperformance_charging_status
              - entity: sensor.auto_temperature
                name: SisaLampotila
              - entity: binary_sensor.530e_iperformance_door_lock_state
                name: Lukot
                #- type: history-graph
                #  title: Battery Status
                #  entities:
                #   - sensor.530e_iperformance_charging_level_hv
                #      - type: glance
                #        title: Auto
                #        entities:
                #          - lock.530e_iperformance_lock
                #          - sensor.530e_iperformance_charging_level_hv
                #          - binary_sensor.530e_iperformance_connection_status
                #          - sensor.530e_iperformance_remaining_range_total
                #          - sensor.auto_temperature
                #          - sensor.auto_humidity

  - icon: mdi:air-conditioner
    title: ilmanvaihto
    type: vertical-stack
    cards:
       - type: glance
         entities:
           - entity: sensor.iv_raitisilman_lampotila
             name: Ulkolampotila
           - entity: sensor.iv_poistoilman_kosteus_x5
             name: Kosteus, Poisto
           - entity: switch.iv_tehostus
             name: Tehostus
           - entity: sensor.iv_todellinen_teho
             name: Teho
           - entity: switch.iv_poissa
             name: Poissa
             tap_action: toggle

       - type: glance
         entities:
           - entity: switch.iv_jaahdytys_sallittu
             name: Jaahdytys Sallittu
             tap_action: toggle
           - entity: switch.iv_lammitus_sallittu
             name: Lammitys Sallittu
             tap_action: toggle
           - entity: switch.iv_pitkaan_poissa
             name: Pitkaan Poissa
             tap_action: toggle
           - entity: switch.iv_kosteus_tehostus
             name: Kosteus Tehostus
             tap_action: toggle
           - entity: sensor.iv_tilatieto
             name: Tila

       - type: entities
         entities:
           - entity: sensor.iv_48h_kosteustason_keskiarvo
           - entity: sensor.iv_jateilman_lampotila_x4
           - entity: sensor.iv_lampotilan_saatoportaat
           - entity: sensor.iv_lto_hyotysuhde_poistopuolella
           - entity: sensor.iv_lto_hyotysuhde_tulopuolella
           - entity: sensor.iv_op1_lampomittaus_paalla
           - entity: sensor.iv_paluuveden_lampotila_x8
           - entity: sensor.iv_poistoilman_lampotila_ennen_lto_x8
           - entity: sensor.iv_poistoilman_lampotila_x5
           - entity: sensor.iv_tuloilman_lampotila_lton_jalkeen_x2
           - entity: sensor.iv_tuloilman_lampotila_x3
           - entity: switch.iv_lampotila_tehostus
             #- entity: switch.iv_liesituuletin
             #card:
             #  title: Ilmanvaihto

  - icon: mdi:car
    type: vertical-stack
    cards:
       - type: picture-entity
         title: BMW 530e
         image: https://cdn.drivemag.net/media/default/0001/42/bmw-5-series-530e-iperformance-06-9939-default-large.jpeg
         entity: sensor.530e_iperformance_mileage
         name: Mileage
       - type: glance
         entities: 
          - entity: sensor.530e_iperformance_charging_level_hv
            name: Varaus
          - entity: sensor.530e_iperformance_remaining_range_total
            name: Range
          - sensor.530e_iperformance_charging_status
            #- binary_sensor.530e_iperformance_charging_status
          - entity: sensor.auto_temperature
            name: SisaLampotila
          - entity: binary_sensor.530e_iperformance_door_lock_state
            name: Lukot
            #- type: history-graph
            #  title: Battery Status
            #  entities:
            #   - sensor.530e_iperformance_charging_level_hv

#  - icon: mdi:car
#    cards:
#       - type: entities
#         entities:
#           - group.bmw530e

  - icon: mdi:washing-machine
    cards:
       - type: glance
         title: Pesukone Kaynnissa
         entities:
           - binary_sensor.washing_machine_running
       - type: entity-filter
         filter:
           - entity_id: '*philio*'
         card_config:
           title: Pyykinpesukone

  - icon: mdi:garage
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*fibaro_system_fgms001zw5*'
         card_config:
           title: Liiketunnistin

  - icon: mdi:chip
    cards:
       - type: entity-filter
         filter:
           - entity_id: '*temperature*'
         card_config:
           title: Lampotilat
       - type: entity-filter
         filter:
           - entity_id: '*humidity*'
         card_config:
           title: Kosteus
       - type: entity-filter
         filter:
           - entity_id: '*battery*'
         card_config:
           title: Patterit

# sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power


    # Specify a tab_icon if you want the view tab to be an icon.
#  - icon: mdi:home-assistant
#    # Name of the view. Will be used as the tooltip for tab icon
#    name: Second view
#    cards:
#      - type: entities
#        title: Lots of Kitchen AC
#        entities:
#            # It is totally possible to render duplicates.
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen
#          - input_boolean.switch_ac_kitchen

